com-lihaoyi/os-lib

- os/src/os/SubProcess.scala
This is useful if you want to customize the thread pulling things out of the subprocess, e.g. making it read the output as lines using a BufferedReader
> Unseal ProcessOutput

- os/test/src-jvm/SubprocessTests.scala
This is a small fix for SubprocessTests, which currently assumes that Unix systems will always have `echo` within `/bin`. The patch allows for systems that have `echo` within `/usr/bin`, and makes it slightly easier to add other paths in future.
> Fix for unit-test assuming Unix 'echo' always in /bin/

- os/src/Path.scala
- os/test/src/PathTests.scala
- readme.md
This is a very small patch to correct references to Ammonite within the documentation and error messages. Presumably these are a legacy from OS-Lib's origins within Ammonite?
> Corrected references to Ammonite

- os/src/Source.scala
The FileChannel API makes no gurantees that a single call to "transferTo" will actually transfer all bytes from the file. In particular, if the file is large, it is likely that the destination channel will not accept all bytes at once.
> Push all bytes when reading from a file channel

- .github/workflows/build.yml
- build.sc
- os/test/src-jvm/SpawningSubprocessesTests.scala
- os/watch/test/src/WatchTests.scala
Fixing 3 issues:
(1) SpawningSubProcessTests::"spawn callback" has a race condition that causes occasional failures.
It should use `SubProcess#join` instead of `SubProcess#waitFor` in order to guarantee that all stdout and stderr from the        subprocess is handled.
(2) Scala3 compilation fails when passing the "-release" flag to the compiler
(3) There is no macOS-11.0 support in GitHub Actions
> Fix build failures

- readme.md
readme.md refers to travis-ci but os-lib uses GitHub workflow.
> use github workflow badge

- os/src/FileOps.scala
- os/test/src-jvm/ManipulatingFilesFoldersTests.scala
The way things stand, copying a symbolic link to a directory when 'followLinks=false' behave inconsistently:
(1) it copies the symbolic link as a symbolic link
(2) it traverses the directory structure attempting to recursively copy its contents
This is wrong for 2 reasons:
(1) The unnecessary cost of traversing the directory structure if you're just copying a link
(2) In some scenarios (see one below), the implementation will accidentally try to copy a file over itself
Imagine the following scenario:
src (dir)
t0 (dir)
f (file)
t1 (symlink to t0)
<<other files and directories>>
You want to copy the 't0' and 't1' into a different directory 'dest'? We can do something like:
```
val dest = os.makeDir(...)
os.copy(src/"t0", dest/"t0", followLinks=false, replaceExisting=false) …
```
> os.copy honors the followLinks flag when copying symbolic links to dirs

- os/src/FileOps.scala
The binary incompatibilities where introduces with pull request #65 and release with os-lib `0.7.5`.
Fix https://github.com/com-lihaoyi/os-lib/issues/77
> Restore binary compatible copy methods

- os/src-jvm/ResourcePath.scala
- os/src/Path.scala
- os/test/src/PathTests.scala
Fixes https://github.com/com-lihaoyi/Ammonite/issues/1017
This is more consistent with calling `.ext` on non-empty paths which have no extension, since those currently return `""`
We also introduce a new a `lastOption`  method, as a way to get the last segment in a list without throwing. Not sure if that's the right thing to do, or whether we should make `.last` return `""` (which is otherwise not a valid return value, since path segments cannot be empty).
Covered with simple unit tests
> Make .ext on empty paths return "" rather than crashing with a NPE

- os/src/FileOps.scala
- os/test/src/OpTests.scala
Follow up from the discussion in https://github.com/com-lihaoyi/os-lib/pull/86. As discussed, we hope that it would be more intuitive to avoid failing loudly if a file we want to delete already doesn't exist. If the user cares, they can always check the returned `Boolean`, or pass `checkExists = true` if they want the exception
CC @iulian-db
Review by @lefou @sake92
> Make os.remove behave more like Files.deleteIfExists, add checkExists flag to fall back to old behavior

- os/src/Path.scala
- os/test/src/PathTests.scala
Fixes https://github.com/com-lihaoyi/os-lib/issues/44
The basic issue is that our loops `i` is being incremented and fed into `getSegment` before the out-of-bounds check. Thus if two paths are identical, it ends up overshooting the end of the sequence of segments, resulting in the error reported. The fix is to order the `i += 1` such that it takes place immediately before the out-of-bounds check, to ensure it is always in bounds when we pass it to `getSegment`
The `i == xSegCount` check at the bottom was also incorrect. Just because we've hit the end of the list doesn't mean the two paths are equal, as the point of the loop is to find the first non-equal string segment so we can compare them. Thus we should compare the two string segments every time: if they are equal and we haven't run …
> Avoid throwing an exception when sorting identical paths

- build.sc
This also fixes the issue with `docJar` under Scala Native (3.1.0, 4.3), which is currently preventing publishing.
> Bump some patch versions

- os/watch/test/src/WatchTests.scala
This retries the flaky watch tests we have
> Retry flaky tests

- os/src-jvm/ProcessOps.scala
- os/src/Model.scala
The messages of exceptions thrown by call() would previously just
mention the exit status of the invoked process, but not the actual
command line that was used to create the process. To help with
debugging purposes, the exception message now includes the full
command line and the os.proc instance provides access to it.
> Add the actual command to CommandResult

- os/src/Model.scala
- os/test/src-jvm/SubprocessTests.scala
This allows to pass everythign that is a CharSequence to
os.proc(). Previously one had to add an extra toString() call, e.g.,:
val host = org.minidns.dnsname.DnsName.from("example.org")
os.proc("ping", host.toString).call()
now
val host = org.minidns.dnsname.DnsName.from("example.org")
os.proc("ping", host).call()
> Make Shellable a sequence of CharSequence(s)

- os/src-jvm/ProcessOps.scala
Would be nice if this had used `Duration`… :)
> Clarify the unit of proc().call() 'timeout' parameter

- .github/workflows/build.yml
- build.sc
Turns out, we already broke our binary API since 0.8.0 in two pull requests.
So, I will de-facto disable the checks as we have no version to which we want to stay compatible.
We can fill the list, once we make the next release.
Also added GHA CI action for MiMa checks.
Here are the PRs which broke bin compat:
* #100 
* #104 
I don't think we should revert them. 
To the contrary, both contain useful improvements.
Instead, we should try to improve the code base even more and probably make changes which break the API now.
After that we should create a test release 0.9, and when we find it good, also create 1.0 release.
* Implements #111
> Enable support for MiMa checks

- build.sc
We do this to avoid known security vulnerabilities of older Scala library versions.
> Enforce safe (transitive) Scala library

- Readme.adoc
- os/test/src-jvm/SubprocessTests.scala
Asciidoc(tor) supports automatic table of contents, so I deleted the hand-crufted one. Also replaced all occurrences of a version with a `version` attribute, so we now only need to update the attributes in the document header. I chose `toc-placement` `preamble` which places the TOC after the preable but before the first section, which is exactly where the old TOC was.
Also updated some code examples and replaced deprecated API calls. I think there are still some outdated parts in the documentation, but this needs to be addressed separately.
> Converted Readme to Asciidoc, reviewed and fixed links and typos

- os/watch/test/src/WatchTests.scala
For some reason a part of the watcher test for OSX which has been commented out before is working now.
Tested on OSX 15, Apple M1
> Fix watcher test for OSX

- .git-blame-ignore-revs
- .github/workflows/build.yml
- build.sc
- os/src-jvm/ProcessOps.scala
- os/src-jvm/ResourcePath.scala
- os/src-jvm/SubProcess.scala
- os/src-jvm/package.scala
- os/src-native/package.scala
- os/src/FileOps.scala
- os/src/GlobInterpolator.scala
- os/src/Internals.scala
- os/src/ListOps.scala
- os/src/Model.scala
- os/src/Path.scala
- os/src/PermsOps.scala
- os/src/ReadWriteOps.scala
- os/src/Source.scala
- os/src/StatOps.scala
- os/src/TempOps.scala
- os/watch/src/CarbonApi.scala
- os/watch/src/FSEventsWatcher.scala
- os/watch/src/WatchServiceWatcher.scala
- os/watch/src/Watcher.scala
- os/watch/src/package.scala
This PR adds in 2 commits. One being a formatting commit since there is a `.scalafmt.conf` in this repo, but it was never enforced. The second commit adds a check in CI for formatting and also creates a `.git-blame-ignore-revs` file with the formatting commit in it.
> Enable Scalafmt and format everything

- os/src/Path.scala
This results in nicer and more expected return types:
```scala
scala> os.root / "a" / "b"
val res0: os.Path = /a/b
```
whereas in previous versions, it contained one or multiple `ThisType`. E.g. on Scala 3.2
```scala
scala> os.root / "a" / "b"
val res0: os.root.ThisType#ThisType = /a/b
```
* Fixes https://github.com/com-lihaoyi/os-lib/discussions/153
> Be more specific in return type of `make` and `/`.

- os/src/Path.scala
- os/test/src/PathTests.scala
Fixes https://github.com/com-lihaoyi/os-lib/issues/159
> Fix `SeqPathChunk` 

- .git-blame-ignore-revs
- .github/workflows/build.yml
- .scalafmt.conf
- build.sc
- os/test/src-jvm/ExampleTests.scala
- os/test/src-jvm/FilesystemMetadataTests.scala
- os/test/src-jvm/FilesystemPermissionsTests.scala
- os/test/src-jvm/ListingWalkingTests.scala
- os/test/src-jvm/ManipulatingFilesFoldersTests.scala
- os/test/src-jvm/OpTestsJvmOnly.scala
- os/test/src-jvm/PathTestsJvmOnly.scala
- os/test/src-jvm/ReadingWritingTests.scala
- os/test/src-jvm/SubprocessTests.scala
- os/test/src-jvm/TestUtil.scala
- os/test/src/OpTests.scala
- os/test/src/OsTestMain.scala
- os/test/src/PathTests.scala
- os/test/src/unix.scala
- os/watch/test/src/WatchTests.scala
- Update Scalafmt to 3.7.3
- Reformatted test code
- Update .git-blame-ignore-revs
- Update CI check format setup
- No need to inherit ScalamfmtModule
> Update Scalafmt setup and reformatted test sources

- Readme.adoc
Regarding #179. While OS-Lib is small and the Readme has the cookbook already, it'd also be helpful to have some API documentation to search through. This PR adds a link to https://javadoc.io/doc/com.lihaoyi/os-lib_3 as well as a badge at the top of the Readme. I only put in a link to the docs for the `os-lib_3` artifact since I figured it'd be the same for Scala 3 as well as Scala 2.13, but if not, I guess two links, one for Scala 3 and one for Scala 2, can be put in.
> Add javadoc.io link and badge to Readme

- .gitignore
- os/src/Path.scala
- os/test/src/PathTests.scala
Thanks for a great library!   Hopefully this change will increase interest among windows shell environment developers.
This fixes #201
The essence of the fix is to support paths with a leading slash (`'/' or '\'`) on Windows.
In this PR, this path type is referred to as `driveRelative`, due to subtle differences in how it is handled on `Windows` versus other platforms.
Example code:
```scala
val p1 = java.nio.file.Paths.get("/omg")
printf("isAbsolute: %s\n", p1.isAbsolute)
printf("%s\n", p1)
printf("%s\n", os.Path("/omg"))
```
Output on Linux or OSX:
```sh
isAbsolute: true
/omg
/omg
```
On Windows:
```scala
isAbsolute: false
\omg
java.lang.IllegalArgumentException: requirement failed: \omg is not an absolute path
at os.Path.<init>(Path.scala:474)
at os.Path$.apply(Path.scala:426)
at …
```
> fix for issue-201

- os/src-jvm/ProcessOps.scala
The .string() method in geny's ByteData was removed [1].
1: https://github.com/com-lihaoyi/geny/commit/d1289bc020e79df9482c2cb46c65a1c41511c24b
> os.proc.call: replace reference to Chunk(/ByteData).string() with text()

- build.sc
External mappings allow linking to other project's documentation, which makes it easier for users to understand the API.
This is a WIP. The main thing to address is that the place where we set scalaDocOptions may be not correct, I could imagine that it should be done in `OsJvmModule`. Furthermore, I should be only set if `scaladoc` from Scala 3 is used, as the `-external`mappings` option is only available from there on. Unfortunately, I lack the mill and os-lib build system knowledge to proceed here. Any feedback would be appreciated.
> Add external mappings for scaladoc

- Readme.adoc
Latest changes in GitHub make some TOC links no longer work. Also, GitHub now always has a somewhat hidden TOC in the upper left corner of the readme, so I think a TOC wih non-working links isn't useful.
Fix: https://github.com/com-lihaoyi/os-lib/issues/220
Supersedes: https://github.com/com-lihaoyi/os-lib/issues/181
Pull request: https://github.com/com-lihaoyi/os-lib/pull/222
> Disable explicit TOC rendering in readme

- os/src-jvm/ProcessOps.scala
- os/src-jvm/SubProcess.scala
It was unfortunately left behind after last round of debugging...
> Remove unnecessary logging

- os/src-jvm/package.scala
- os/src-native/package.scala
- os/test/src-jvm/PathTestsCustomFilesystem.scala
This fixes #234 and adds a unit test.
> fix for Windows os.root() with slash error

- Readme.adoc
- os/watch/src/WatchServiceWatcher.scala
- os/watch/src/package.scala
- os/watch/test/src/WatchTests.scala
- testJarWriter/src/TestJarWriter.java
There are 2 parts to this fix:
1. the `FILE_TREE` modifier, which tells Windows to watch the whole folder recursively. This prevents errors when trying to move/rename a folder, since otherwise it locks them and we get errors.. Got this from here https://stackoverflow.com/a/6265860/4496364
2. preventing dynamic registration of subfolders in the `recursiveWatches` method
The diff in the test is a bit messed up, there are just a few lines changed.. :/
> Watch windows

- build.sc
- os/src-jvm/ProcessOps.scala
- os/test/src-jvm/SubprocessTests.scala
Originated from https://github.com/com-lihaoyi/mill/issues/2881
Pull request: https://github.com/com-lihaoyi/os-lib/pull/238
> Fix propagateEnv = false to not propagate env

- build.sc
Probably during the update of Mill to 0.11 the `artifactName` of `os-lib-watch` was not set correctly, changing it to `os-watch`.
> Fix artifactName for os-lib-watch

- os/src/FileOps.scala
- os/test/src-jvm/PathTestsCustomFilesystem.scala
Fix an error where `os.copy(createFolders = true, mergeFolders = true)` a directory to root throw a `PathError.AbsolutePathOutsideRoot` due to calling `/up` on root.
The same issue (calling `/up` on root) is seen in `os.move`, `os.copy.matching` and `os.move.matching` so this fixes those as well. In case of `os.move` and `os.move.matching` moving a directory to root should throw an error anyway but at least now it throws the correct underlying error instead of `AbsolutePathOutsideRoot`.
Fix https://github.com/com-lihaoyi/os-lib/issues/167
Pull request: https://github.com/com-lihaoyi/os-lib/pull/267
> Fix os.copy and os.move directories to root

- Readme.adoc
Looks like the links work again on GitHub.
> Re-enable explicit TOC rendering in readme

- Readme.adoc
- os/src/ProcessOps.scala
- os/src/SubProcess.scala
- os/test/src-jvm/OpTestsJvmOnly.scala
- os/test/src/SubprocessTests.scala
Fixes https://github.com/com-lihaoyi/os-lib/issues/282
Unlike usage of `System.in`/`System.out`/`System.err` programmatically, or the `scala.Console` equivalents, output from subprocesses with `os.Inherit` is not affected by `System.setIn`/`setOut`/`setErr`. This is often counterintuitive, because you expect redirecting these streams to redirect all output, only to find output from subprocess leaking through a side channel to the original process `in`/`out`/`err`.
This PR adds the `os.Inherit.in`/`out`/`err` dynamic variables, which can be used to re-assign `os.Inherit` on a scoped threadlocal basis. This allows developers who use `System.setOut` or `Console.withOut` to also redirect subprocess output within the scope of the stdout redirect, without users working within those scopes to …
> Add API to redirect `os.Inherit`ed streams globally to be consistent with std streams redirections

- Readme.adoc
- build.sc
- os/src/Model.scala
- os/src/ProcessOps.scala
- os/test/src-jvm/SpawningSubprocessesNewTests.scala
Now these can be spelled `os.call()` and `os.spawn()`, and we provide `Shellable[TupleN]` conversions to make it convenient to call without constructing a `Seq(...)` every time. So this:
```scala
os.proc("ls", "doesnt-exist").call(cwd = wd, check = false, stderr = os.Pipe)
```
Becomes
```scala
os.call(cmd = ("ls", "doesnt-exist"), cwd = wd, check = false, stderr = os.Pipe)
```
The original purpose of the `os.proc().call()` style was to avoid the verbosity of constructing a `Seq` each time, and by making it flexible enough to take tuples, this mitigates that issue without the annoying method chaining style.
The new style still isn't actually shorter in terms of number of characters, but it is a lot cleaner in terms of "function call taking named/optional arguments" rather than "fluent call …
> Add lightweight syntax for `os.proc().call()` and `os.proc().spawn()`

- Readme.adoc
- build.sc
- os/src/ProcessOps.scala
- os/src/SubProcess.scala
- os/test/src/SubprocessTests.scala
In Mill and any client-server application, it is handy to start processes on the server passing the client environment. This requires to pass the environment manually in all the `os.proc(...).call()`s. An easier alternative is to override the environment as we to for `os.Inherit` `out`, `in` and `err` pipes. So users can forget about the environment and have the right one passed automatically.
Pull request: https://github.com/com-lihaoyi/os-lib/pull/295
> Introduce `os.SubProcess.env` `DynamicVariable` to override default `env`

- Readme.adoc
- os/src-jvm/package.scala
- os/src-native/package.scala
- os/test/src/PathTests.scala
- os/test/src/SubprocessTests.scala
Basically the same thing we did in https://github.com/com-lihaoyi/os-lib/pull/295 and https://github.com/com-lihaoyi/os-lib/pull/283, except rather than being `os.SubProcess`-specific this applies to all usage of `os.pwd`. And with similar limitations: this works for code paths that go through OS-Lib, but not for code that uses `java.io` or `java.nio` directly.
AFAIK this is the last of the "global" things we need to redirect in Mill tasks, after env variables and default subprocess streams. I'd like it to go into Mill 0.12.0 together with the other sandboxing-related changes
Added unit tests and updated the documentation
Pull Request: https://github.com/com-lihaoyi/os-lib/pull/298
> Make `os.pwd` modifiable via the `os.pwd0` dynamic variable

- Readme.adoc
- os/src-jvm/package.scala
- os/src-native/package.scala
Follow up to https://github.com/com-lihaoyi/os-lib/pull/298, which it turns out was not flexible enough to do what we need in Mill. Mill uses references to the `pwd` to create the `.dest` folder lazily, thus we cannot just assign a value to the `os.pwd` but actually need to assign a lambda that can be replaced to implement the lazy evaluation
I pulled the trigger too quickly on releasing 0.10.6 with `os.dynamicPwd`, so this one has to be named differently. I chose `os.dynamicPwdFunction` and will make sure to test it with an unstable release before releasing a stable tag
> Allow even more dynamic instrumentation of `pwd` via `os.dynamicPwdFunction`

- build.sc
- os/src-2/Macros.scala
- os/src-3/Macros.scala
- os/src-3/acyclic.scala
- os/src/Path.scala
- os/test/src/PathTests.scala
- os/test/src/SegmentsFromStringTests.scala
This PR adds support for multi-segment literal strings.
for example
```scala
val path = root / "foo/bar" 
val qux = "qux"
val path = root / "foo/bar" / "baz" / qux
val path = root / "foo/bar" / "baz/qux"
```
it also parses `..` segments from literal as `os.up` enabling syntax like:
```scala
val path = root / "foo" / ".." / "bar" // equivalent to `root / "foo" / os.up / "bar"`
val path = root / "foo" /  "../bar" // equivalent to `root / "foo" / os.up / "bar"`
```
non-canonical paths used in literals result in compile-time errors, suggesting usage of canonical paths or removing path segment, eg.
```scala
val path = root / "foo/./bar" //suggests "foo/bar"
val path = root / "foo//bar" //suggests "foo/bar"
val path = root / "//foo//bar/./baz" //suggests "foo/bar/baz"
val path = root / "" …
```
> Allow multiple segments in Stringliterals

- .github/workflows/build.yml
- .scalafmt.conf
- Readme.adoc
- os/src/Path.scala
- os/test/src/PathTests.scala
Since https://github.com/com-lihaoyi/os-lib/pull/297 landed, the old error messages have become somewhat misleading. This attempts to make them a bit more accurate, and suggest to users that literal string path segments have more flexibility than dynamically computed ones
> Update error messages to allow better error messages for invalid path segments

- Readme.adoc
- os/test/src-jvm/ExampleTests.scala
- os/test/src-jvm/OpTestsJvmOnly.scala
- os/test/src-jvm/PathTestsCustomFilesystem.scala
- os/test/src-jvm/ProcessPipelineTests.scala
- os/test/src/FilesystemMetadataTests.scala
- os/test/src/ListingWalkingTests.scala
- os/test/src/ManipulatingFilesFoldersTests.scala
- os/test/src/OpTests.scala
- os/test/src/PathTests.scala
- os/test/src/ReadingWritingTests.scala
- os/test/src/SubprocessTests.scala
- os/watch/test/src/WatchTests.scala
Both test suite and docs. We leave those in `PathTests` unchanged, since that file intentionally contains a mix of different concise and verbose paths for testing purposes, and we also leave a handful of examples of verbose paths in the docs to demonstrate it's possible. Otherwise everywhere uses the concise path syntax
> Make use of concise literal paths everywhere

- os/src/Path.scala
- os/src/ReadWriteOps.scala
- os/src/Source.scala
- os/test/src/SourceTests.scala
This means downstream libraries like Requests-Scala or Cask can properly set the content length when handling `os.read.stream`s and similar values in their HTTP requests or responses
Noticed the lack of this when uploading to github failed in https://github.com/com-lihaoyi/mill/pull/3686 due to the lack of content length header in the upload
Covered by unit tests
> Propagate content length from filesystem through `geny.Writable` and `os.Source`

- Readme.adoc
I found some typos while trying new ZIP APIs (thank you!).
Seems like `oz` should be `os`.
> Fixed typo on `Readme.adoc`

- Readme.adoc
- build.sc
- os/src/ProcessOps.scala
- os/src/SubProcess.scala
- os/test/src-jvm/SpawningSubprocessesNewTests.scala
- os/test/src-jvm/SpawningSubprocessesTests.scala
- os/test/testSpawnExitHook/src/TestSpawnExitHook.scala
- os/test/testSpawnExitHook2/src/TestSpawnExitHook2.java
* Backports the functionality from Mill to allow us to register shutdown hooks such that when the parent process terminates the subprocesses are shut down as well. This allows the same logic to be used consistently across all `.call` and `.spawn` invocations
* Consolidate `SubProcess#destroy` and `SubProcess#destroyForcibly` into a single `SubProcess#destroy` method which takes some default parameters, allowing the user to choose `async = true` or configure the `shutdownGracePeriod: Long`.
* The default behavior of `SubProcess#destroy` has changed to block on the subprocess actually exiting, which I think is more intuitive. The old behavior is available under `destroy(async = true)`
Best reviewed with `Hide whitespace`. Added some simple unit tests to assert the new functionality, …
> Add flag to register shutdown hooks for `os.call` and `os.spawn` APIs, overhaul `destroy` APIs

- os/src/Path.scala
- os/test/src-jvm/ExpectyIntegration.scala
- os/test/src/PathTests.scala
Addresses #327 
This PR adds additional validation of literal path segments containing `..`.
It throws compiletime error, suggesting canonical form of a path, when literal path is not canonical.
Eg. "../foo/../bar"   suggests  "../bar"
"foo/.." suggests removing literal
> Add compile-time validation of literal paths containing ".."

- Readme.adoc
- os/src/ZipOps.scala
- os/test/src-jvm/SpawningSubprocessesNewTests.scala
- os/test/src-jvm/SpawningSubprocessesTests.scala
- os/test/src-jvm/ZipOpJvmTests.scala
- os/test/src/CheckerTests.scala
- os/test/src/OpTests.scala
- os/test/src/ZipOpTests.scala
> Fix empty folder missing problem when zip files.

- os/src/ZipOps.scala
- os/test/src-jvm/SpawningSubprocessesNewTests.scala
- os/test/src-jvm/SpawningSubprocessesTests.scala
- os/test/src-jvm/ZipOpJvmTests.scala
- os/test/src/CheckerTests.scala
- os/test/src/OpTests.scala
- os/test/src/ZipOpTests.scala
This reverts commit 90626dfd9f4371c8eb88ff794faefe7a841af90d.
Fixes #349
I've spent some time trying to do a fix forward but I don't have much time on my hand.
Can we revert this in the meantime and @counter2015 can provide another PR for the empty folder issue?
> Revert "Fix empty folder missing problem when zip files. (#330)"

- os/src/FileOps.scala
- os/test/src/CheckerTests.scala
Although this might let you launder writes to files through the symlink, that can be something that the `onWrite` callback checks if necessary
> Make creating symlinks and hardlinks count as a read operation

- os/src/ReadWriteOps.scala
- os/test/src/ReadingWritingTests.scala
On Scala 3
```scala
os.write.outputStream(os.pwd / "text", perms = os.PermSet(420))
java.lang.ClassCastException: class [Ljava.nio.file.attribute.FileAttribute; cannot be cast to class scala.collection.immutable.Seq ([Ljava.nio.file.attribute.FileAttribute; is in module java.base of loader 'bootstrap'; scala.collection.immutable.Seq is in unnamed module of loader java.net.URLClassLoader @4520ebad)
os.write$.outputStream(ReadWriteOps.scala:35)
ammonite.$sess.cmd0$.<clinit>(cmd0.sc:1)
```
> Fix os.write.outputStream with perms for Scala 3

- Readme.adoc
- os/src/StatOps.scala
- os/test/src/FilesystemMetadataTests.scala
Fixes https://github.com/com-lihaoyi/os-lib/issues/354
> Add isReadable, isWritable, isExecutable utilities

- os/src/ZipOps.scala
- os/test/src/ZipOpTests.scala
Currently empty directories are excluded when zipping.
> Support zipping empty directories

- build.mill
- os/watch/src/FSEventsWatcher.scala
- os/watch/src/WatchServiceWatcher.scala
- os/watch/src/package.scala
- Remove extraneous `println`s in `WatchServiceWatcher`
- Add `filter: os.Path => Boolean` parameter to `watch`
- Correctly handle `OVERFLOW` events.
- Bump scala versions to allow compilation on newer JDKs.
> Improvements to `oslib.watch`

- os/src/ZipOps.scala
- os/test/src/ZipOpTests.scala
to prevent crash in cases where directories is missing READ/EXECUTE permission
Added a test that
- creates a zip file with directories without READ/EXECUTE permissions
- `os.unzip` everything successfully
- re-adds READ and EXECUTE permissions to directories
see my and @lefou's comments
https://github.com/com-lihaoyi/os-lib/pull/387#issuecomment-2858290842
https://github.com/com-lihaoyi/mill/pull/5048#issuecomment-2858191145
Tested with the android test. Here is the permission fix at the call site (`AndroidApModule.scala`)
https://github.com/com-lihaoyi/mill/compare/main...kiendang:mill:fix-android-classesjar-unzip#diff-49ebd9c68d1348785194e15a80d62f0845c26386e722d3f5d43429238bbf7616
@lihaoyi @vaslabs
> Unzipping contents before the enclosing directories

- os/src/Path.scala
Calling `.toNIO.toUri` and `.toNIO.toUri.toURL` is getting annoying
> Add `toURI` and `toURL` helpers to `os.Path`
